---
title: "R Notebook"
output: html_notebook
---

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

```{r,message=FALSE, warning=FALSE}
library(xlsx)
library(reshape2)
library(dplyr)

library("rvest")
library("tibble")
library("qdap")
library("sentimentr")
library("gplots")
library("tm")
library("syuzhet")
library("factoextra")
library("beeswarm")
library("scales")
library("RColorBrewer")
library("RANN")
library("tm")
library("topicmodels")

source("../lib/plotstacked.R")
source("../lib/speechFuncs.R")


```

```{r,message=FALSE, warning=FALSE}
dates <- read.table("../data/InauguationDates.txt", header = TRUE, fill = TRUE, sep = "\t")
info <- read.xlsx("../data/InaugurationInfo.xlsx", 1,header = TRUE)

getwd()

dates2 <- melt(dates, id = "PRESIDENT")
dates2$variable <- as.numeric(as.factor(dates2$variable))
del <- which(dates2$value == "")
dates2 <- dates2[-del, ]

# Manually change some presidents' names, to make names identical in two dataframes
dates2$PRESIDENT <- as.character(dates2$PRESIDENT)
info$President <- as.character(info$President)
dates2[8,1] <- toString("Martin van Buren")
dates2[11,1] <- toString("James K. Polk")
dates2[20,1] <- toString("James Garfield")
info[25,1] <- toString("Grover Cleveland")
info[27,1] <- toString("Grover Cleveland")
dates2[which(dates2$PRESIDENT == "Richard M. Nixon"),1] <- "Richard Nixon"

# Merge df based on president and term
speech <- info %>%
  left_join(dates2, by = c("President" = "PRESIDENT")) %>%
  filter(Term == variable)
speech<- speech[,-which(colnames(speech) =="variable")]
colnames(speech)[6] <- "Date"

# Harry S. Truman's speech is missing from the file
speech <- speech[-41, ]
```

```{r,message=FALSE, warning=FALSE}
# Combine the correspoinding speech into the df
speech$Fulltext <- NA
combtext <- function(df){
  exp <- paste("../data/InauguralSpeeches/inaug",df[2],"-",df[3],".txt",sep = "")
  return(paste(readLines(exp), collapse = " "))
}

speech$Fulltext <- apply(speech,1,combtext)
```

```{r,message=FALSE, warning=FALSE}
sentence.list=NULL
for(i in 1:nrow(speech)){
  sentences=sent_detect(speech$Fulltext[i],
                        endmarks = c("?", ".", "!", "|",";"))
  if(length(sentences)>0){
    emotions=get_nrc_sentiment(sentences)
    word.count=word_count(sentences)
    # colnames(emotions)=paste0("emo.", colnames(emotions))
    # in case the word counts are zeros?
    emotions=diag(1/(word.count+0.01))%*%as.matrix(emotions)
    sentence.list=rbind(sentence.list, 
                        cbind(speech[i,-ncol(speech)],
                              sentences=as.character(sentences), 
                              word.count,
                              emotions,
                              sent.id=1:length(sentences)
                              )
    )
  }
}
```

